<?php namespace Anomaly\Streams\Platform\Model\News;

use Anomaly\Streams\Platform\Entry\EntryModel;

class NewsNewsEntryModel extends EntryModel
{

    use \Illuminate\Database\Eloquent\SoftDeletes;

    protected $searchable = true;

    protected $versionable = true;

    protected $table = 'news_news';

    protected $titleName = 'title';

    protected $rules = [
        'title' => 'required',
        'slug' => 'required',
        'publish_at' => '',
        'category' => 'required',
        'hide_header' => '',
        'image' => '',
        'locale' => '',
        'content' => '',
        'enabled' => '',
];

    protected $fields = [
        'title',
        'slug',
        'publish_at',
        'category',
        'hide_header',
        'image',
        'locale',
        'content',
        'enabled',
];

    protected $with = [];

    protected $dates = ['created_at', 'updated_at', 'publish_at', 'deleted_at'];

    protected $relationships = ['category', 'image', 'content'];

    

    

    

    protected $stream = [
'id' => '54',
'sort_order' => '',
'namespace' => 'news',
'slug' => 'news',
'prefix' => 'news_',
'title_column' => 'title',
'order_by' => 'id',
'locked' => '0',
'hidden' => '0',
'sortable' => '0',
'searchable' => '1',
'trashable' => '1',
'translatable' => '0',
'versionable' => '1',
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'assignments' => [
[
'id' => 238,
'sort_order' => 1,
'stream_id' => 54,
'field_id' => 204,
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'unique' => 0,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '204',
'namespace' => 'news',
'slug' => 'title',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 303,
'field_id' => 204,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 304,
'field_id' => 204,
'locale' => 'en',
'name' => 'Title',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 305,
'field_id' => 204,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 306,
'field_id' => 204,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 376,
'assignment_id' => 238,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 377,
'assignment_id' => 238,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 378,
'assignment_id' => 238,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 379,
'assignment_id' => 238,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 239,
'sort_order' => 2,
'stream_id' => 54,
'field_id' => 205,
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'unique' => 0,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '205',
'namespace' => 'news',
'slug' => 'slug',
'type' => 'anomaly.field_type.slug',
'config' => 'a:5:{s:4:"type";s:1:"-";s:7:"slugify";s:5:"title";s:9:"lowercase";b:1;s:3:"min";N;s:3:"max";N;}',
'locked' => '0',
'translations' => [
[
'id' => 307,
'field_id' => 205,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 308,
'field_id' => 205,
'locale' => 'en',
'name' => 'Slug',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 309,
'field_id' => 205,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 310,
'field_id' => 205,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 380,
'assignment_id' => 239,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 381,
'assignment_id' => 239,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 382,
'assignment_id' => 239,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 383,
'assignment_id' => 239,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 259,
'sort_order' => 3,
'stream_id' => 54,
'field_id' => 218,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '218',
'namespace' => 'news',
'slug' => 'publish_at',
'type' => 'anomaly.field_type.datetime',
'config' => 'a:6:{s:4:"mode";s:8:"datetime";s:6:"picker";b:1;s:11:"date_format";s:5:"Y-m-d";s:11:"time_format";s:3:"H:i";s:8:"timezone";s:3:"UTC";s:4:"step";s:1:"1";}',
'locked' => '0',
'translations' => [
[
'id' => 359,
'field_id' => 218,
'locale' => 'ar',
'name' => 'Publish at',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 360,
'field_id' => 218,
'locale' => 'en',
'name' => 'Publish at',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 361,
'field_id' => 218,
'locale' => 'de',
'name' => 'Publish at',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 362,
'field_id' => 218,
'locale' => 'es',
'name' => 'Publish at',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 460,
'assignment_id' => 259,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 461,
'assignment_id' => 259,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 462,
'assignment_id' => 259,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 463,
'assignment_id' => 259,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 257,
'sort_order' => 4,
'stream_id' => 54,
'field_id' => 216,
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'unique' => 0,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '216',
'namespace' => 'news',
'slug' => 'category',
'type' => 'anomaly.field_type.relationship',
'config' => 'a:3:{s:7:"related";s:60:"Anomaly\Streams\Platform\Model\News\NewsCategoriesEntryModel";s:4:"mode";s:8:"dropdown";s:10:"title_name";s:5:"title";}',
'locked' => '0',
'translations' => [
[
'id' => 351,
'field_id' => 216,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 352,
'field_id' => 216,
'locale' => 'en',
'name' => 'Category',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 353,
'field_id' => 216,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 354,
'field_id' => 216,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 452,
'assignment_id' => 257,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 453,
'assignment_id' => 257,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 454,
'assignment_id' => 257,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 455,
'assignment_id' => 257,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 407,
'sort_order' => 5,
'stream_id' => 54,
'field_id' => 305,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '305',
'namespace' => 'news',
'slug' => 'hide_header',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:7:{s:4:"mode";s:6:"switch";s:5:"label";N;s:7:"on_text";N;s:8:"on_color";s:7:"success";s:8:"off_text";N;s:9:"off_color";s:7:"default";s:13:"default_value";b:0;}',
'locked' => '0',
'translations' => [
[
'id' => 707,
'field_id' => 305,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 708,
'field_id' => 305,
'locale' => 'en',
'name' => 'Hide header',
'placeholder' => '',
'warning' => '',
'instructions' => 'This switch hide header in inner page',
],
[
'id' => 709,
'field_id' => 305,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 710,
'field_id' => 305,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 1049,
'assignment_id' => 407,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1050,
'assignment_id' => 407,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1051,
'assignment_id' => 407,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1052,
'assignment_id' => 407,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 253,
'sort_order' => 6,
'stream_id' => 54,
'field_id' => 215,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '215',
'namespace' => 'news',
'slug' => 'image',
'type' => 'anomaly.field_type.image',
'config' => 'a:3:{s:7:"folders";a:1:{i:0;s:1:"1";}s:12:"aspect_ratio";N;s:4:"mode";s:7:"default";}',
'locked' => '0',
'translations' => [
[
'id' => 347,
'field_id' => 215,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 348,
'field_id' => 215,
'locale' => 'en',
'name' => 'Image',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 349,
'field_id' => 215,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 350,
'field_id' => 215,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 436,
'assignment_id' => 253,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 437,
'assignment_id' => 253,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 438,
'assignment_id' => 253,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 439,
'assignment_id' => 253,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 241,
'sort_order' => 7,
'stream_id' => 54,
'field_id' => 207,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '207',
'namespace' => 'news',
'slug' => 'locale',
'type' => 'anomaly.field_type.select',
'config' => 'a:4:{s:4:"mode";s:8:"dropdown";s:7:"options";s:26:"en:EN
de:DE
es:ES
ar:AR";s:9:"separator";N;s:13:"default_value";s:2:"en";}',
'locked' => '0',
'translations' => [
[
'id' => 315,
'field_id' => 207,
'locale' => 'ar',
'name' => 'Locale',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 316,
'field_id' => 207,
'locale' => 'en',
'name' => 'Locale',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 317,
'field_id' => 207,
'locale' => 'de',
'name' => 'Locale',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 318,
'field_id' => 207,
'locale' => 'es',
'name' => 'Locale',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 388,
'assignment_id' => 241,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 389,
'assignment_id' => 241,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 390,
'assignment_id' => 241,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 391,
'assignment_id' => 241,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 243,
'sort_order' => 8,
'stream_id' => 54,
'field_id' => 209,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '209',
'namespace' => 'news',
'slug' => 'content',
'type' => 'anomaly.field_type.grid',
'config' => 'a:4:{s:7:"related";N;s:7:"add_row";N;s:3:"min";N;s:3:"max";N;}',
'locked' => '0',
'translations' => [
[
'id' => 323,
'field_id' => 209,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 324,
'field_id' => 209,
'locale' => 'en',
'name' => 'Content',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 325,
'field_id' => 209,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 326,
'field_id' => 209,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 396,
'assignment_id' => 243,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 397,
'assignment_id' => 243,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 398,
'assignment_id' => 243,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 399,
'assignment_id' => 243,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 258,
'sort_order' => 9,
'stream_id' => 54,
'field_id' => 217,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '217',
'namespace' => 'news',
'slug' => 'enabled',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:7:{s:4:"mode";s:6:"switch";s:5:"label";N;s:7:"on_text";N;s:8:"on_color";s:7:"success";s:8:"off_text";N;s:9:"off_color";s:7:"default";s:13:"default_value";b:0;}',
'locked' => '0',
'translations' => [
[
'id' => 355,
'field_id' => 217,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 356,
'field_id' => 217,
'locale' => 'en',
'name' => 'Enabled',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 357,
'field_id' => 217,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 358,
'field_id' => 217,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 456,
'assignment_id' => 258,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 457,
'assignment_id' => 258,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 458,
'assignment_id' => 258,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 459,
'assignment_id' => 258,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
],
'translations' => [
[
'id' => 102,
'stream_id' => 54,
'locale' => 'ar',
'name' => '',
'description' => '',
],
[
'id' => 103,
'stream_id' => 54,
'locale' => 'en',
'name' => 'News',
'description' => '',
],
[
'id' => 104,
'stream_id' => 54,
'locale' => 'de',
'name' => '',
'description' => '',
],
[
'id' => 105,
'stream_id' => 54,
'locale' => 'es',
'name' => '',
'description' => '',
],
],
];

    
    /**
     * The category relation
     *
     * @return Relation
     */
    public function category()
    {
        return $this->getFieldType('category')->getRelation();
    }

    /**
     * The image relation
     *
     * @return Relation
     */
    public function image()
    {
        return $this->getFieldType('image')->getRelation();
    }

    /**
     * The content relation
     *
     * @return Relation
     */
    public function content()
    {
        return $this->getFieldType('content')->getRelation();
    }

}
