<?php namespace Anomaly\Streams\Platform\Model\Pages;

use Anomaly\Streams\Platform\Entry\EntryModel;

class PagesAboutUsPagesEntryModel extends EntryModel
{

    use \Illuminate\Database\Eloquent\SoftDeletes;

    protected $searchable = false;

    protected $versionable = false;

    protected $table = 'pages_about_us_pages';

    protected $titleName = 'id';

    protected $rules = [
        'header_image' => '',
        'additional_text' => '',
        'about_us_section_1' => '',
        'about_us_section_2' => '',
        'about_us_section_3' => '',
        'youtube_url' => '',
        'youtube_title' => '',
        'youtube_thumbnail' => '',
        'achievements_text' => '',
        'projects_count' => '',
        'countries_count' => '',
        'team_count' => '',
        'partners_count' => '',
        'quality_commitment_text' => '',
        'quality_commitment_logos' => '',
        'partners_text' => '',
        'partners' => '',
];

    protected $fields = [
        'header_image',
        'additional_text',
        'about_us_section_1',
        'about_us_section_2',
        'about_us_section_3',
        'youtube_url',
        'youtube_title',
        'youtube_thumbnail',
        'achievements_text',
        'projects_count',
        'countries_count',
        'team_count',
        'partners_count',
        'quality_commitment_text',
        'quality_commitment_logos',
        'partners_text',
        'partners',
];

    protected $with = ["translations"];

    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    protected $relationships = ['header_image', 'youtube_thumbnail', 'quality_commitment_logos', 'partners'];

    

    protected $translationForeignKey = 'entry_id';

    protected $translationModel = 'Anomaly\Streams\Platform\Model\Pages\PagesAboutUsPagesEntryTranslationsModel';

    protected $stream = [
'id' => '77',
'sort_order' => '',
'namespace' => 'pages',
'slug' => 'about_us_pages',
'prefix' => 'pages_',
'title_column' => 'id',
'order_by' => 'id',
'locked' => '0',
'hidden' => '1',
'sortable' => '0',
'searchable' => '0',
'trashable' => '1',
'translatable' => '1',
'versionable' => '0',
'config' => 'a:0:{}',
'assignments' => [
[
'id' => 311,
'sort_order' => 1,
'stream_id' => 77,
'field_id' => 225,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '225',
'namespace' => 'pages',
'slug' => 'header_image',
'type' => 'anomaly.field_type.image',
'config' => 'a:3:{s:7:"folders";a:1:{i:0;s:1:"1";}s:12:"aspect_ratio";N;s:4:"mode";s:7:"default";}',
'locked' => '0',
'translations' => [
[
'id' => 387,
'field_id' => 225,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 388,
'field_id' => 225,
'locale' => 'en',
'name' => 'Header image',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 389,
'field_id' => 225,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 390,
'field_id' => 225,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 665,
'assignment_id' => 311,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 666,
'assignment_id' => 311,
'locale' => 'en',
'label' => 'Top Image',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 667,
'assignment_id' => 311,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 668,
'assignment_id' => 311,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 312,
'sort_order' => 2,
'stream_id' => 77,
'field_id' => 241,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '241',
'namespace' => 'pages',
'slug' => 'additional_text',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 451,
'field_id' => 241,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 452,
'field_id' => 241,
'locale' => 'en',
'name' => 'Additional Text',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 453,
'field_id' => 241,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 454,
'field_id' => 241,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 669,
'assignment_id' => 312,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 670,
'assignment_id' => 312,
'locale' => 'en',
'label' => 'Text Below Top Image',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 671,
'assignment_id' => 312,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 672,
'assignment_id' => 312,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 313,
'sort_order' => 3,
'stream_id' => 77,
'field_id' => 247,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '247',
'namespace' => 'pages',
'slug' => 'about_us_section_1',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 475,
'field_id' => 247,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 476,
'field_id' => 247,
'locale' => 'en',
'name' => 'About us section 1',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 477,
'field_id' => 247,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 478,
'field_id' => 247,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 673,
'assignment_id' => 313,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 674,
'assignment_id' => 313,
'locale' => 'en',
'label' => 'Purpose Text',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 675,
'assignment_id' => 313,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 676,
'assignment_id' => 313,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 314,
'sort_order' => 4,
'stream_id' => 77,
'field_id' => 248,
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '248',
'namespace' => 'pages',
'slug' => 'about_us_section_2',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 479,
'field_id' => 248,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 480,
'field_id' => 248,
'locale' => 'en',
'name' => 'About us section 2',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 481,
'field_id' => 248,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 482,
'field_id' => 248,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 677,
'assignment_id' => 314,
'locale' => 'ar',
'label' => 'Mission Text',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 678,
'assignment_id' => 314,
'locale' => 'en',
'label' => 'Vision Text',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 679,
'assignment_id' => 314,
'locale' => 'de',
'label' => 'Mission Text',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 680,
'assignment_id' => 314,
'locale' => 'es',
'label' => 'Mission Text',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 315,
'sort_order' => 5,
'stream_id' => 77,
'field_id' => 249,
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '249',
'namespace' => 'pages',
'slug' => 'about_us_section_3',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 483,
'field_id' => 249,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 484,
'field_id' => 249,
'locale' => 'en',
'name' => 'About us section 3',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 485,
'field_id' => 249,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 486,
'field_id' => 249,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 681,
'assignment_id' => 315,
'locale' => 'ar',
'label' => 'Vision Text',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 682,
'assignment_id' => 315,
'locale' => 'en',
'label' => 'Mission Text',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 683,
'assignment_id' => 315,
'locale' => 'de',
'label' => 'Vision Text',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 684,
'assignment_id' => 315,
'locale' => 'es',
'label' => 'Vision Text',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 316,
'sort_order' => 6,
'stream_id' => 77,
'field_id' => 235,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '235',
'namespace' => 'pages',
'slug' => 'youtube_url',
'type' => 'anomaly.field_type.url',
'config' => 'a:1:{s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 427,
'field_id' => 235,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 428,
'field_id' => 235,
'locale' => 'en',
'name' => 'Youtube URL',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 429,
'field_id' => 235,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 430,
'field_id' => 235,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 685,
'assignment_id' => 316,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 686,
'assignment_id' => 316,
'locale' => 'en',
'label' => 'About us Video',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 687,
'assignment_id' => 316,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 688,
'assignment_id' => 316,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 317,
'sort_order' => 7,
'stream_id' => 77,
'field_id' => 236,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '236',
'namespace' => 'pages',
'slug' => 'youtube_title',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 431,
'field_id' => 236,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 432,
'field_id' => 236,
'locale' => 'en',
'name' => 'Youtube Title',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 433,
'field_id' => 236,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 434,
'field_id' => 236,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 689,
'assignment_id' => 317,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 690,
'assignment_id' => 317,
'locale' => 'en',
'label' => 'About us video Title',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 691,
'assignment_id' => 317,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 692,
'assignment_id' => 317,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 318,
'sort_order' => 8,
'stream_id' => 77,
'field_id' => 234,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '234',
'namespace' => 'pages',
'slug' => 'youtube_thumbnail',
'type' => 'anomaly.field_type.image',
'config' => 'a:3:{s:7:"folders";a:1:{i:0;s:1:"1";}s:12:"aspect_ratio";N;s:4:"mode";s:7:"default";}',
'locked' => '0',
'translations' => [
[
'id' => 423,
'field_id' => 234,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 424,
'field_id' => 234,
'locale' => 'en',
'name' => 'Youtube thumbnail',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 425,
'field_id' => 234,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 426,
'field_id' => 234,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 693,
'assignment_id' => 318,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 694,
'assignment_id' => 318,
'locale' => 'en',
'label' => 'About us video Thumb',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 695,
'assignment_id' => 318,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 696,
'assignment_id' => 318,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 319,
'sort_order' => 9,
'stream_id' => 77,
'field_id' => 250,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '250',
'namespace' => 'pages',
'slug' => 'achievements_text',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 487,
'field_id' => 250,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 488,
'field_id' => 250,
'locale' => 'en',
'name' => 'Achievements text',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 489,
'field_id' => 250,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 490,
'field_id' => 250,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 697,
'assignment_id' => 319,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 698,
'assignment_id' => 319,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 699,
'assignment_id' => 319,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 700,
'assignment_id' => 319,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 320,
'sort_order' => 10,
'stream_id' => 77,
'field_id' => 251,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '251',
'namespace' => 'pages',
'slug' => 'projects_count',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 491,
'field_id' => 251,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 492,
'field_id' => 251,
'locale' => 'en',
'name' => 'Projects count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 493,
'field_id' => 251,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 494,
'field_id' => 251,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 701,
'assignment_id' => 320,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 702,
'assignment_id' => 320,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 703,
'assignment_id' => 320,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 704,
'assignment_id' => 320,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 321,
'sort_order' => 11,
'stream_id' => 77,
'field_id' => 243,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '243',
'namespace' => 'pages',
'slug' => 'countries_count',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 459,
'field_id' => 243,
'locale' => 'ar',
'name' => 'Countries count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 460,
'field_id' => 243,
'locale' => 'en',
'name' => 'Countries count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 461,
'field_id' => 243,
'locale' => 'de',
'name' => 'Countries count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 462,
'field_id' => 243,
'locale' => 'es',
'name' => 'Countries count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 705,
'assignment_id' => 321,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 706,
'assignment_id' => 321,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 707,
'assignment_id' => 321,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 708,
'assignment_id' => 321,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 322,
'sort_order' => 12,
'stream_id' => 77,
'field_id' => 242,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '242',
'namespace' => 'pages',
'slug' => 'team_count',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 455,
'field_id' => 242,
'locale' => 'ar',
'name' => 'Team count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 456,
'field_id' => 242,
'locale' => 'en',
'name' => 'Team count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 457,
'field_id' => 242,
'locale' => 'de',
'name' => 'Team count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 458,
'field_id' => 242,
'locale' => 'es',
'name' => 'Team count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 709,
'assignment_id' => 322,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 710,
'assignment_id' => 322,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 711,
'assignment_id' => 322,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 712,
'assignment_id' => 322,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 323,
'sort_order' => 13,
'stream_id' => 77,
'field_id' => 252,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '252',
'namespace' => 'pages',
'slug' => 'partners_count',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 495,
'field_id' => 252,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 496,
'field_id' => 252,
'locale' => 'en',
'name' => 'Partners count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 497,
'field_id' => 252,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 498,
'field_id' => 252,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 713,
'assignment_id' => 323,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 714,
'assignment_id' => 323,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 715,
'assignment_id' => 323,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 716,
'assignment_id' => 323,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 324,
'sort_order' => 14,
'stream_id' => 77,
'field_id' => 253,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '253',
'namespace' => 'pages',
'slug' => 'quality_commitment_text',
'type' => 'anomaly.field_type.textarea',
'config' => 'a:6:{s:4:"rows";s:1:"6";s:3:"min";N;s:3:"max";N;s:12:"show_counter";b:0;s:8:"autogrow";b:1;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 499,
'field_id' => 253,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 500,
'field_id' => 253,
'locale' => 'en',
'name' => 'Quality commitment Text',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 501,
'field_id' => 253,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 502,
'field_id' => 253,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 717,
'assignment_id' => 324,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 718,
'assignment_id' => 324,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 719,
'assignment_id' => 324,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 720,
'assignment_id' => 324,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 325,
'sort_order' => 15,
'stream_id' => 77,
'field_id' => 254,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '254',
'namespace' => 'pages',
'slug' => 'quality_commitment_logos',
'type' => 'anomaly.field_type.files',
'config' => 'a:5:{s:7:"folders";a:1:{i:0;s:1:"1";}s:3:"min";N;s:3:"max";N;s:4:"mode";s:7:"default";s:13:"allowed_types";a:4:{i:0;s:3:"png";i:1;s:3:"jpg";i:2;s:4:"jpeg";i:3;s:3:"svg";}}',
'locked' => '0',
'translations' => [
[
'id' => 503,
'field_id' => 254,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 504,
'field_id' => 254,
'locale' => 'en',
'name' => 'Quality commitment Logos',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 505,
'field_id' => 254,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 506,
'field_id' => 254,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 721,
'assignment_id' => 325,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 722,
'assignment_id' => 325,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 723,
'assignment_id' => 325,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 724,
'assignment_id' => 325,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 332,
'sort_order' => 16,
'stream_id' => 77,
'field_id' => 255,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '255',
'namespace' => 'pages',
'slug' => 'partners_text',
'type' => 'anomaly.field_type.textarea',
'config' => 'a:6:{s:4:"rows";s:1:"6";s:3:"min";N;s:3:"max";N;s:12:"show_counter";b:0;s:8:"autogrow";b:1;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 507,
'field_id' => 255,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 508,
'field_id' => 255,
'locale' => 'en',
'name' => 'Partners Text',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 509,
'field_id' => 255,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 510,
'field_id' => 255,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 749,
'assignment_id' => 332,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 750,
'assignment_id' => 332,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 751,
'assignment_id' => 332,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 752,
'assignment_id' => 332,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 331,
'sort_order' => 17,
'stream_id' => 77,
'field_id' => 257,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '257',
'namespace' => 'pages',
'slug' => 'partners',
'type' => 'anomaly.field_type.repeater',
'config' => 'a:5:{s:7:"related";s:66:"Anomaly\Streams\Platform\Model\Repeater\RepeaterPartnersEntryModel";s:7:"add_row";s:11:"Add partner";s:3:"min";N;s:3:"max";N;s:14:"repeater_title";N;}',
'locked' => '0',
'translations' => [
[
'id' => 515,
'field_id' => 257,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 516,
'field_id' => 257,
'locale' => 'en',
'name' => 'Partners',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 517,
'field_id' => 257,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 518,
'field_id' => 257,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 745,
'assignment_id' => 331,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 746,
'assignment_id' => 331,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 747,
'assignment_id' => 331,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 748,
'assignment_id' => 331,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
],
'translations' => [
[
'id' => 191,
'stream_id' => 77,
'locale' => 'en',
'name' => 'About us',
'description' => 'About us page template',
],
],
];

    
    /**
     * The header image relation
     *
     * @return Relation
     */
    public function headerImage()
    {
        return $this->getFieldType('header_image')->getRelation();
    }

    /**
     * The youtube thumbnail relation
     *
     * @return Relation
     */
    public function youtubeThumbnail()
    {
        return $this->getFieldType('youtube_thumbnail')->getRelation();
    }

    /**
     * The quality commitment logos relation
     *
     * @return Relation
     */
    public function qualityCommitmentLogos()
    {
        return $this->getFieldType('quality_commitment_logos')->getRelation();
    }

    /**
     * The partners relation
     *
     * @return Relation
     */
    public function partners()
    {
        return $this->getFieldType('partners')->getRelation();
    }

}
