<?php namespace Anomaly\Streams\Platform\Model\Pages;

use Anomaly\Streams\Platform\Entry\EntryModel;

class PagesCareersPagesEntryModel extends EntryModel
{

    use \Illuminate\Database\Eloquent\SoftDeletes;

    protected $searchable = false;

    protected $versionable = false;

    protected $table = 'pages_careers_pages';

    protected $titleName = 'id';

    protected $rules = [
        'header_image' => '',
        'page_description' => '',
        'team_count' => '',
        'nationalities_count' => '',
        'office_locations_count' => '',
        'founded_in' => '',
        'additional_text' => '',
];

    protected $fields = [
        'header_image',
        'page_description',
        'team_count',
        'nationalities_count',
        'office_locations_count',
        'founded_in',
        'additional_text',
];

    protected $with = ["translations"];

    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    protected $relationships = ['header_image'];

    protected $translatedAttributes = ['page_description', 'additional_text'];

    protected $translationForeignKey = 'entry_id';

    protected $translationModel = 'Anomaly\Streams\Platform\Model\Pages\PagesCareersPagesEntryTranslationsModel';

    protected $stream = [
'id' => '96',
'sort_order' => '',
'namespace' => 'pages',
'slug' => 'careers_pages',
'prefix' => 'pages_',
'title_column' => 'id',
'order_by' => 'id',
'locked' => '0',
'hidden' => '1',
'sortable' => '0',
'searchable' => '0',
'trashable' => '1',
'translatable' => '1',
'versionable' => '0',
'config' => 'a:0:{}',
'assignments' => [
[
'id' => 388,
'sort_order' => 1,
'stream_id' => 96,
'field_id' => 225,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '225',
'namespace' => 'pages',
'slug' => 'header_image',
'type' => 'anomaly.field_type.image',
'config' => 'a:3:{s:7:"folders";a:1:{i:0;s:1:"1";}s:12:"aspect_ratio";N;s:4:"mode";s:7:"default";}',
'locked' => '0',
'translations' => [
[
'id' => 387,
'field_id' => 225,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 388,
'field_id' => 225,
'locale' => 'en',
'name' => 'Header image',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 389,
'field_id' => 225,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 390,
'field_id' => 225,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 973,
'assignment_id' => 388,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 974,
'assignment_id' => 388,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 975,
'assignment_id' => 388,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 976,
'assignment_id' => 388,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 389,
'sort_order' => 2,
'stream_id' => 96,
'field_id' => 289,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '289',
'namespace' => 'pages',
'slug' => 'page_description',
'type' => 'anomaly.field_type.textarea',
'config' => 'a:6:{s:4:"rows";s:1:"6";s:3:"min";N;s:3:"max";N;s:12:"show_counter";b:0;s:8:"autogrow";b:1;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 643,
'field_id' => 289,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 644,
'field_id' => 289,
'locale' => 'en',
'name' => 'Description',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 645,
'field_id' => 289,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 646,
'field_id' => 289,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 977,
'assignment_id' => 389,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 978,
'assignment_id' => 389,
'locale' => 'en',
'label' => 'About us description',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 979,
'assignment_id' => 389,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 980,
'assignment_id' => 389,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 390,
'sort_order' => 3,
'stream_id' => 96,
'field_id' => 242,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '242',
'namespace' => 'pages',
'slug' => 'team_count',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 455,
'field_id' => 242,
'locale' => 'ar',
'name' => 'Team count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 456,
'field_id' => 242,
'locale' => 'en',
'name' => 'Team count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 457,
'field_id' => 242,
'locale' => 'de',
'name' => 'Team count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 458,
'field_id' => 242,
'locale' => 'es',
'name' => 'Team count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 981,
'assignment_id' => 390,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 982,
'assignment_id' => 390,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 983,
'assignment_id' => 390,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 984,
'assignment_id' => 390,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 391,
'sort_order' => 4,
'stream_id' => 96,
'field_id' => 290,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '290',
'namespace' => 'pages',
'slug' => 'nationalities_count',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 647,
'field_id' => 290,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 648,
'field_id' => 290,
'locale' => 'en',
'name' => 'Nationalities count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 649,
'field_id' => 290,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 650,
'field_id' => 290,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 985,
'assignment_id' => 391,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 986,
'assignment_id' => 391,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 987,
'assignment_id' => 391,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 988,
'assignment_id' => 391,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 392,
'sort_order' => 5,
'stream_id' => 96,
'field_id' => 292,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '292',
'namespace' => 'pages',
'slug' => 'office_locations_count',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 655,
'field_id' => 292,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 656,
'field_id' => 292,
'locale' => 'en',
'name' => 'Office locations Count',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 657,
'field_id' => 292,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 658,
'field_id' => 292,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 989,
'assignment_id' => 392,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 990,
'assignment_id' => 392,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 991,
'assignment_id' => 392,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 992,
'assignment_id' => 392,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 393,
'sort_order' => 6,
'stream_id' => 96,
'field_id' => 291,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '291',
'namespace' => 'pages',
'slug' => 'founded_in',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 651,
'field_id' => 291,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 652,
'field_id' => 291,
'locale' => 'en',
'name' => 'Founded in',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 653,
'field_id' => 291,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 654,
'field_id' => 291,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 993,
'assignment_id' => 393,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 994,
'assignment_id' => 393,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 995,
'assignment_id' => 393,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 996,
'assignment_id' => 393,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 394,
'sort_order' => 7,
'stream_id' => 96,
'field_id' => 241,
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '241',
'namespace' => 'pages',
'slug' => 'additional_text',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 451,
'field_id' => 241,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 452,
'field_id' => 241,
'locale' => 'en',
'name' => 'Additional Text',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 453,
'field_id' => 241,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 454,
'field_id' => 241,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 997,
'assignment_id' => 394,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => 'Text below count section',
],
[
'id' => 998,
'assignment_id' => 394,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => 'Text below count section',
],
[
'id' => 999,
'assignment_id' => 394,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => 'Text below count section',
],
[
'id' => 1000,
'assignment_id' => 394,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => 'Text below count section',
],
],
],
],
'translations' => [
[
'id' => 261,
'stream_id' => 96,
'locale' => 'en',
'name' => 'Careers',
'description' => 'Jobs + job inner popup page template',
],
],
];

    
    /**
     * The header image relation
     *
     * @return Relation
     */
    public function headerImage()
    {
        return $this->getFieldType('header_image')->getRelation();
    }

}
