<?php namespace Anomaly\Streams\Platform\Model\Pages;

use Anomaly\Streams\Platform\Entry\EntryModel;

class PagesHomepagePagesEntryModel extends EntryModel
{

    use \Illuminate\Database\Eloquent\SoftDeletes;

    protected $searchable = false;

    protected $versionable = false;

    protected $table = 'pages_homepage_pages';

    protected $titleName = 'id';

    protected $rules = [
        'dates_and_facts' => '',
        'header_image' => '',
        'top_image_1_text' => '',
        'top_image_1_url' => '',
        'top_image_2_text' => '',
        'top_image_2_url' => '',
        'top_image_3_text' => '',
        'top_image_3_url' => '',
        'top_image_4_text' => '',
        'top_image_4_url' => '',
        'benefits_title' => '',
        'benefits' => '',
        'bottom_blocks' => '',
        'youtube_title' => '',
        'youtube_url' => '',
        'youtube_thumbnail' => '',
];

    protected $fields = [
        'dates_and_facts',
        'header_image',
        'top_image_1_text',
        'top_image_1_url',
        'top_image_2_text',
        'top_image_2_url',
        'top_image_3_text',
        'top_image_3_url',
        'top_image_4_text',
        'top_image_4_url',
        'benefits_title',
        'benefits',
        'bottom_blocks',
        'youtube_title',
        'youtube_url',
        'youtube_thumbnail',
];

    protected $with = ["translations"];

    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    protected $relationships = ['dates_and_facts', 'header_image', 'benefits', 'bottom_blocks', 'youtube_thumbnail'];

    protected $translatedAttributes = ['top_image_1_text', 'top_image_1_url', 'top_image_2_text', 'top_image_2_url', 'top_image_3_text', 'top_image_3_url', 'top_image_4_text', 'top_image_4_url', 'benefits_title', 'youtube_title'];

    protected $translationForeignKey = 'entry_id';

    protected $translationModel = 'Anomaly\Streams\Platform\Model\Pages\PagesHomepagePagesEntryTranslationsModel';

    protected $stream = [
'id' => '53',
'sort_order' => '',
'namespace' => 'pages',
'slug' => 'homepage_pages',
'prefix' => 'pages_',
'title_column' => 'id',
'order_by' => 'id',
'locked' => '0',
'hidden' => '1',
'sortable' => '0',
'searchable' => '0',
'trashable' => '1',
'translatable' => '1',
'versionable' => '0',
'config' => 'a:0:{}',
'assignments' => [
[
'id' => 271,
'sort_order' => 1,
'stream_id' => 53,
'field_id' => 226,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '226',
'namespace' => 'pages',
'slug' => 'dates_and_facts',
'type' => 'anomaly.field_type.repeater',
'config' => 'a:5:{s:7:"related";s:75:"Anomaly\Streams\Platform\Model\Repeater\RepeaterAcmeDatesAndFactsEntryModel";s:7:"add_row";N;s:3:"min";N;s:3:"max";N;s:14:"repeater_title";N;}',
'locked' => '0',
'translations' => [
[
'id' => 391,
'field_id' => 226,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 392,
'field_id' => 226,
'locale' => 'en',
'name' => 'Dates & Facts',
'placeholder' => '',
'warning' => '',
'instructions' => 'Enter date and its main fact',
],
[
'id' => 393,
'field_id' => 226,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 394,
'field_id' => 226,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 508,
'assignment_id' => 271,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 509,
'assignment_id' => 271,
'locale' => 'en',
'label' => 'Dates & Facts',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 510,
'assignment_id' => 271,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 511,
'assignment_id' => 271,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 268,
'sort_order' => 2,
'stream_id' => 53,
'field_id' => 225,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '225',
'namespace' => 'pages',
'slug' => 'header_image',
'type' => 'anomaly.field_type.image',
'config' => 'a:3:{s:7:"folders";a:1:{i:0;s:1:"1";}s:12:"aspect_ratio";N;s:4:"mode";s:7:"default";}',
'locked' => '0',
'translations' => [
[
'id' => 387,
'field_id' => 225,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 388,
'field_id' => 225,
'locale' => 'en',
'name' => 'Header image',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 389,
'field_id' => 225,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 390,
'field_id' => 225,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 496,
'assignment_id' => 268,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 497,
'assignment_id' => 268,
'locale' => 'en',
'label' => 'Header image',
'warning' => '',
'placeholder' => '',
'instructions' => 'Image that show on top of the page',
],
[
'id' => 498,
'assignment_id' => 268,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 499,
'assignment_id' => 268,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 365,
'sort_order' => 3,
'stream_id' => 53,
'field_id' => 276,
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '276',
'namespace' => 'pages',
'slug' => 'top_image_1_text',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 591,
'field_id' => 276,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 592,
'field_id' => 276,
'locale' => 'en',
'name' => 'Top image 1 Text',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 593,
'field_id' => 276,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 594,
'field_id' => 276,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 881,
'assignment_id' => 365,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 882,
'assignment_id' => 365,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 883,
'assignment_id' => 365,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 884,
'assignment_id' => 365,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 369,
'sort_order' => 4,
'stream_id' => 53,
'field_id' => 280,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '280',
'namespace' => 'pages',
'slug' => 'top_image_1_url',
'type' => 'anomaly.field_type.url',
'config' => 'a:1:{s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 607,
'field_id' => 280,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 608,
'field_id' => 280,
'locale' => 'en',
'name' => 'Top image 1 URL',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 609,
'field_id' => 280,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 610,
'field_id' => 280,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 897,
'assignment_id' => 369,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 898,
'assignment_id' => 369,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 899,
'assignment_id' => 369,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 900,
'assignment_id' => 369,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 366,
'sort_order' => 5,
'stream_id' => 53,
'field_id' => 277,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '277',
'namespace' => 'pages',
'slug' => 'top_image_2_text',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 595,
'field_id' => 277,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 596,
'field_id' => 277,
'locale' => 'en',
'name' => 'Top image 2 Text',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 597,
'field_id' => 277,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 598,
'field_id' => 277,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 885,
'assignment_id' => 366,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 886,
'assignment_id' => 366,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 887,
'assignment_id' => 366,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 888,
'assignment_id' => 366,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 370,
'sort_order' => 6,
'stream_id' => 53,
'field_id' => 281,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '281',
'namespace' => 'pages',
'slug' => 'top_image_2_url',
'type' => 'anomaly.field_type.url',
'config' => 'a:1:{s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 611,
'field_id' => 281,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 612,
'field_id' => 281,
'locale' => 'en',
'name' => 'Top image 2 URL',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 613,
'field_id' => 281,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 614,
'field_id' => 281,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 901,
'assignment_id' => 370,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 902,
'assignment_id' => 370,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 903,
'assignment_id' => 370,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 904,
'assignment_id' => 370,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 367,
'sort_order' => 7,
'stream_id' => 53,
'field_id' => 278,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '278',
'namespace' => 'pages',
'slug' => 'top_image_3_text',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 599,
'field_id' => 278,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 600,
'field_id' => 278,
'locale' => 'en',
'name' => 'Top image 3 Text',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 601,
'field_id' => 278,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 602,
'field_id' => 278,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 889,
'assignment_id' => 367,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 890,
'assignment_id' => 367,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 891,
'assignment_id' => 367,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 892,
'assignment_id' => 367,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 371,
'sort_order' => 8,
'stream_id' => 53,
'field_id' => 282,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '282',
'namespace' => 'pages',
'slug' => 'top_image_3_url',
'type' => 'anomaly.field_type.url',
'config' => 'a:1:{s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 615,
'field_id' => 282,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 616,
'field_id' => 282,
'locale' => 'en',
'name' => 'Top image 3 URL',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 617,
'field_id' => 282,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 618,
'field_id' => 282,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 905,
'assignment_id' => 371,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 906,
'assignment_id' => 371,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 907,
'assignment_id' => 371,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 908,
'assignment_id' => 371,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 368,
'sort_order' => 9,
'stream_id' => 53,
'field_id' => 279,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '279',
'namespace' => 'pages',
'slug' => 'top_image_4_text',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 603,
'field_id' => 279,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 604,
'field_id' => 279,
'locale' => 'en',
'name' => 'Top image 4 Text',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 605,
'field_id' => 279,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 606,
'field_id' => 279,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 893,
'assignment_id' => 368,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 894,
'assignment_id' => 368,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 895,
'assignment_id' => 368,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 896,
'assignment_id' => 368,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 372,
'sort_order' => 10,
'stream_id' => 53,
'field_id' => 283,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '283',
'namespace' => 'pages',
'slug' => 'top_image_4_url',
'type' => 'anomaly.field_type.url',
'config' => 'a:1:{s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 619,
'field_id' => 283,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 620,
'field_id' => 283,
'locale' => 'en',
'name' => 'Top image 4 URL',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 621,
'field_id' => 283,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 622,
'field_id' => 283,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 909,
'assignment_id' => 372,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 910,
'assignment_id' => 372,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 911,
'assignment_id' => 372,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 912,
'assignment_id' => 372,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 236,
'sort_order' => 11,
'stream_id' => 53,
'field_id' => 202,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '202',
'namespace' => 'pages',
'slug' => 'benefits_title',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 292,
'field_id' => 202,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 293,
'field_id' => 202,
'locale' => 'en',
'name' => 'Benefits title',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 294,
'field_id' => 202,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 295,
'field_id' => 202,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 368,
'assignment_id' => 236,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 369,
'assignment_id' => 236,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 370,
'assignment_id' => 236,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 371,
'assignment_id' => 236,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 237,
'sort_order' => 12,
'stream_id' => 53,
'field_id' => 203,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '203',
'namespace' => 'pages',
'slug' => 'benefits',
'type' => 'anomaly.field_type.multiple',
'config' => 'a:5:{s:7:"related";s:66:"Anomaly\Streams\Platform\Model\Benefits\BenefitsBenefitsEntryModel";s:4:"mode";s:6:"lookup";s:10:"title_name";s:5:"title";s:3:"min";N;s:3:"max";s:1:"4";}',
'locked' => '0',
'translations' => [
[
'id' => 296,
'field_id' => 203,
'locale' => 'ar',
'name' => 'Benefits',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 297,
'field_id' => 203,
'locale' => 'en',
'name' => 'Benefits',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 298,
'field_id' => 203,
'locale' => 'de',
'name' => 'Benefits',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 299,
'field_id' => 203,
'locale' => 'es',
'name' => 'Benefits',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 372,
'assignment_id' => 237,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 373,
'assignment_id' => 237,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 374,
'assignment_id' => 237,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 375,
'assignment_id' => 237,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 278,
'sort_order' => 13,
'stream_id' => 53,
'field_id' => 231,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '231',
'namespace' => 'pages',
'slug' => 'bottom_blocks',
'type' => 'anomaly.field_type.repeater',
'config' => 'a:5:{s:7:"related";s:78:"Anomaly\Streams\Platform\Model\Repeater\RepeaterHomePageBottomBlocksEntryModel";s:7:"add_row";s:7:"Add new";s:3:"min";N;s:3:"max";N;s:14:"repeater_title";N;}',
'locked' => '0',
'translations' => [
[
'id' => 411,
'field_id' => 231,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 412,
'field_id' => 231,
'locale' => 'en',
'name' => 'Bottom blocks',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 413,
'field_id' => 231,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 414,
'field_id' => 231,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 536,
'assignment_id' => 278,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 537,
'assignment_id' => 278,
'locale' => 'en',
'label' => 'Bottom blocks',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 538,
'assignment_id' => 278,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 539,
'assignment_id' => 278,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 281,
'sort_order' => 14,
'stream_id' => 53,
'field_id' => 236,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '236',
'namespace' => 'pages',
'slug' => 'youtube_title',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 431,
'field_id' => 236,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 432,
'field_id' => 236,
'locale' => 'en',
'name' => 'Youtube Title',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 433,
'field_id' => 236,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 434,
'field_id' => 236,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 548,
'assignment_id' => 281,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 549,
'assignment_id' => 281,
'locale' => 'en',
'label' => 'Youtube Title',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 550,
'assignment_id' => 281,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 551,
'assignment_id' => 281,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 282,
'sort_order' => 15,
'stream_id' => 53,
'field_id' => 235,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '235',
'namespace' => 'pages',
'slug' => 'youtube_url',
'type' => 'anomaly.field_type.url',
'config' => 'a:1:{s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 427,
'field_id' => 235,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 428,
'field_id' => 235,
'locale' => 'en',
'name' => 'Youtube URL',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 429,
'field_id' => 235,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 430,
'field_id' => 235,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 552,
'assignment_id' => 282,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 553,
'assignment_id' => 282,
'locale' => 'en',
'label' => 'Youtube URL',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 554,
'assignment_id' => 282,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 555,
'assignment_id' => 282,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 280,
'sort_order' => 16,
'stream_id' => 53,
'field_id' => 234,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '234',
'namespace' => 'pages',
'slug' => 'youtube_thumbnail',
'type' => 'anomaly.field_type.image',
'config' => 'a:3:{s:7:"folders";a:1:{i:0;s:1:"1";}s:12:"aspect_ratio";N;s:4:"mode";s:7:"default";}',
'locked' => '0',
'translations' => [
[
'id' => 423,
'field_id' => 234,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 424,
'field_id' => 234,
'locale' => 'en',
'name' => 'Youtube thumbnail',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 425,
'field_id' => 234,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 426,
'field_id' => 234,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 544,
'assignment_id' => 280,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 545,
'assignment_id' => 280,
'locale' => 'en',
'label' => 'Youtube Thumbnail',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 546,
'assignment_id' => 280,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 547,
'assignment_id' => 280,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
],
'translations' => [
[
'id' => 101,
'stream_id' => 53,
'locale' => 'en',
'name' => 'Homepage',
'description' => 'Homepage template',
],
],
];

    
    /**
     * The dates and facts relation
     *
     * @return Relation
     */
    public function datesAndFacts()
    {
        return $this->getFieldType('dates_and_facts')->getRelation();
    }

    /**
     * The header image relation
     *
     * @return Relation
     */
    public function headerImage()
    {
        return $this->getFieldType('header_image')->getRelation();
    }

    /**
     * The benefits relation
     *
     * @return Relation
     */
    public function benefits()
    {
        return $this->getFieldType('benefits')->getRelation();
    }

    /**
     * The bottom blocks relation
     *
     * @return Relation
     */
    public function bottomBlocks()
    {
        return $this->getFieldType('bottom_blocks')->getRelation();
    }

    /**
     * The youtube thumbnail relation
     *
     * @return Relation
     */
    public function youtubeThumbnail()
    {
        return $this->getFieldType('youtube_thumbnail')->getRelation();
    }

}
