<?php namespace Anomaly\Streams\Platform\Model\Users;

use Anomaly\Streams\Platform\Entry\EntryModel;

class UsersUsersEntryModel extends EntryModel
{

    use \Illuminate\Database\Eloquent\SoftDeletes;

    protected $searchable = true;

    protected $versionable = false;

    protected $table = 'users_users';

    protected $titleName = 'display_name';

    protected $rules = [
        'email' => 'required|unique:users_users,email',
        'username' => 'required|unique:users_users,username',
        'password' => 'required',
        'roles' => 'required',
        'display_name' => 'required',
        'first_name' => '',
        'last_name' => '',
        'activated' => '',
        'enabled' => '',
        'permissions' => '',
        'last_login_at' => '',
        'remember_token' => '',
        'activation_code' => '',
        'reset_code' => '',
        'last_activity_at' => '',
        'ip_address' => '',
        'str_id' => 'required|unique:users_users,str_id',
];

    protected $fields = [
        'email',
        'username',
        'password',
        'roles',
        'display_name',
        'first_name',
        'last_name',
        'activated',
        'enabled',
        'permissions',
        'last_login_at',
        'remember_token',
        'activation_code',
        'reset_code',
        'last_activity_at',
        'ip_address',
        'str_id',
];

    protected $with = [];

    protected $dates = ['created_at', 'updated_at', 'last_login_at', 'last_activity_at', 'deleted_at'];

    protected $relationships = ['roles'];

    

    

    

    protected $stream = [
'id' => '12',
'sort_order' => '',
'namespace' => 'users',
'slug' => 'users',
'prefix' => 'users_',
'title_column' => 'display_name',
'order_by' => 'id',
'locked' => '0',
'hidden' => '0',
'sortable' => '0',
'searchable' => '1',
'trashable' => '1',
'translatable' => '0',
'versionable' => '0',
'config' => 'a:0:{}',
'assignments' => [
[
'id' => 89,
'sort_order' => 88,
'stream_id' => 12,
'field_id' => 80,
'config' => 'a:0:{}',
'unique' => 1,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '80',
'namespace' => 'users',
'slug' => 'email',
'type' => 'anomaly.field_type.email',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 80,
'field_id' => 80,
'locale' => 'en',
'name' => 'anomaly.module.users::field.email.name',
'placeholder' => 'anomaly.module.users::field.email.placeholder',
'warning' => 'anomaly.module.users::field.email.warning',
'instructions' => 'anomaly.module.users::field.email.instructions',
],
],
],
'translations' => [
[
'id' => 89,
'assignment_id' => 89,
'locale' => 'en',
'label' => 'anomaly.module.users::field.email.label.users',
'warning' => 'anomaly.module.users::field.email.warning.users',
'placeholder' => 'anomaly.module.users::field.email.placeholder.users',
'instructions' => 'anomaly.module.users::field.email.instructions.users',
],
],
],
[
'id' => 90,
'sort_order' => 89,
'stream_id' => 12,
'field_id' => 81,
'config' => 'a:0:{}',
'unique' => 1,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '81',
'namespace' => 'users',
'slug' => 'username',
'type' => 'anomaly.field_type.slug',
'config' => 'a:2:{s:4:"type";s:1:"_";s:9:"lowercase";b:0;}',
'locked' => '1',
'translations' => [
[
'id' => 81,
'field_id' => 81,
'locale' => 'en',
'name' => 'anomaly.module.users::field.username.name',
'placeholder' => 'anomaly.module.users::field.username.placeholder',
'warning' => 'anomaly.module.users::field.username.warning',
'instructions' => 'anomaly.module.users::field.username.instructions',
],
],
],
'translations' => [
[
'id' => 90,
'assignment_id' => 90,
'locale' => 'en',
'label' => 'anomaly.module.users::field.username.label.users',
'warning' => 'anomaly.module.users::field.username.warning.users',
'placeholder' => 'anomaly.module.users::field.username.placeholder.users',
'instructions' => 'anomaly.module.users::field.username.instructions.users',
],
],
],
[
'id' => 91,
'sort_order' => 90,
'stream_id' => 12,
'field_id' => 82,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '82',
'namespace' => 'users',
'slug' => 'password',
'type' => 'anomaly.field_type.text',
'config' => 'a:1:{s:4:"type";s:8:"password";}',
'locked' => '1',
'translations' => [
[
'id' => 82,
'field_id' => 82,
'locale' => 'en',
'name' => 'anomaly.module.users::field.password.name',
'placeholder' => 'anomaly.module.users::field.password.placeholder',
'warning' => 'anomaly.module.users::field.password.warning',
'instructions' => 'anomaly.module.users::field.password.instructions',
],
],
],
'translations' => [
[
'id' => 91,
'assignment_id' => 91,
'locale' => 'en',
'label' => 'anomaly.module.users::field.password.label.users',
'warning' => 'anomaly.module.users::field.password.warning.users',
'placeholder' => 'anomaly.module.users::field.password.placeholder.users',
'instructions' => 'anomaly.module.users::field.password.instructions.users',
],
],
],
[
'id' => 92,
'sort_order' => 91,
'stream_id' => 12,
'field_id' => 100,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '100',
'namespace' => 'users',
'slug' => 'roles',
'type' => 'anomaly.field_type.multiple',
'config' => 'a:1:{s:7:"related";s:34:"Anomaly\UsersModule\Role\RoleModel";}',
'locked' => '1',
'translations' => [
[
'id' => 100,
'field_id' => 100,
'locale' => 'en',
'name' => 'anomaly.module.users::field.roles.name',
'placeholder' => 'anomaly.module.users::field.roles.placeholder',
'warning' => 'anomaly.module.users::field.roles.warning',
'instructions' => 'anomaly.module.users::field.roles.instructions',
],
],
],
'translations' => [
[
'id' => 92,
'assignment_id' => 92,
'locale' => 'en',
'label' => 'anomaly.module.users::field.roles.label.users',
'warning' => 'anomaly.module.users::field.roles.warning.users',
'placeholder' => 'anomaly.module.users::field.roles.placeholder.users',
'instructions' => 'anomaly.module.users::field.roles.instructions.users',
],
],
],
[
'id' => 93,
'sort_order' => 92,
'stream_id' => 12,
'field_id' => 88,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '88',
'namespace' => 'users',
'slug' => 'display_name',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 88,
'field_id' => 88,
'locale' => 'en',
'name' => 'anomaly.module.users::field.display_name.name',
'placeholder' => 'anomaly.module.users::field.display_name.placeholder',
'warning' => 'anomaly.module.users::field.display_name.warning',
'instructions' => 'anomaly.module.users::field.display_name.instructions',
],
],
],
'translations' => [
[
'id' => 93,
'assignment_id' => 93,
'locale' => 'en',
'label' => 'anomaly.module.users::field.display_name.label.users',
'warning' => 'anomaly.module.users::field.display_name.warning.users',
'placeholder' => 'anomaly.module.users::field.display_name.placeholder.users',
'instructions' => 'anomaly.module.users::field.display_name.instructions.users',
],
],
],
[
'id' => 94,
'sort_order' => 93,
'stream_id' => 12,
'field_id' => 89,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '89',
'namespace' => 'users',
'slug' => 'first_name',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 89,
'field_id' => 89,
'locale' => 'en',
'name' => 'anomaly.module.users::field.first_name.name',
'placeholder' => 'anomaly.module.users::field.first_name.placeholder',
'warning' => 'anomaly.module.users::field.first_name.warning',
'instructions' => 'anomaly.module.users::field.first_name.instructions',
],
],
],
'translations' => [
[
'id' => 94,
'assignment_id' => 94,
'locale' => 'en',
'label' => 'anomaly.module.users::field.first_name.label.users',
'warning' => 'anomaly.module.users::field.first_name.warning.users',
'placeholder' => 'anomaly.module.users::field.first_name.placeholder.users',
'instructions' => 'anomaly.module.users::field.first_name.instructions.users',
],
],
],
[
'id' => 95,
'sort_order' => 94,
'stream_id' => 12,
'field_id' => 90,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '90',
'namespace' => 'users',
'slug' => 'last_name',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 90,
'field_id' => 90,
'locale' => 'en',
'name' => 'anomaly.module.users::field.last_name.name',
'placeholder' => 'anomaly.module.users::field.last_name.placeholder',
'warning' => 'anomaly.module.users::field.last_name.warning',
'instructions' => 'anomaly.module.users::field.last_name.instructions',
],
],
],
'translations' => [
[
'id' => 95,
'assignment_id' => 95,
'locale' => 'en',
'label' => 'anomaly.module.users::field.last_name.label.users',
'warning' => 'anomaly.module.users::field.last_name.warning.users',
'placeholder' => 'anomaly.module.users::field.last_name.placeholder.users',
'instructions' => 'anomaly.module.users::field.last_name.instructions.users',
],
],
],
[
'id' => 96,
'sort_order' => 95,
'stream_id' => 12,
'field_id' => 97,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '97',
'namespace' => 'users',
'slug' => 'activated',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:1:{s:13:"default_value";b:0;}',
'locked' => '1',
'translations' => [
[
'id' => 97,
'field_id' => 97,
'locale' => 'en',
'name' => 'anomaly.module.users::field.activated.name',
'placeholder' => 'anomaly.module.users::field.activated.placeholder',
'warning' => 'anomaly.module.users::field.activated.warning',
'instructions' => 'anomaly.module.users::field.activated.instructions',
],
],
],
'translations' => [
[
'id' => 96,
'assignment_id' => 96,
'locale' => 'en',
'label' => 'anomaly.module.users::field.activated.label.users',
'warning' => 'anomaly.module.users::field.activated.warning.users',
'placeholder' => 'anomaly.module.users::field.activated.placeholder.users',
'instructions' => 'anomaly.module.users::field.activated.instructions.users',
],
],
],
[
'id' => 97,
'sort_order' => 96,
'stream_id' => 12,
'field_id' => 98,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '98',
'namespace' => 'users',
'slug' => 'enabled',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:1:{s:13:"default_value";b:1;}',
'locked' => '1',
'translations' => [
[
'id' => 98,
'field_id' => 98,
'locale' => 'en',
'name' => 'anomaly.module.users::field.enabled.name',
'placeholder' => 'anomaly.module.users::field.enabled.placeholder',
'warning' => 'anomaly.module.users::field.enabled.warning',
'instructions' => 'anomaly.module.users::field.enabled.instructions',
],
],
],
'translations' => [
[
'id' => 97,
'assignment_id' => 97,
'locale' => 'en',
'label' => 'anomaly.module.users::field.enabled.label.users',
'warning' => 'anomaly.module.users::field.enabled.warning.users',
'placeholder' => 'anomaly.module.users::field.enabled.placeholder.users',
'instructions' => 'anomaly.module.users::field.enabled.instructions.users',
],
],
],
[
'id' => 98,
'sort_order' => 97,
'stream_id' => 12,
'field_id' => 87,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '87',
'namespace' => 'users',
'slug' => 'permissions',
'type' => 'anomaly.field_type.checkboxes',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 87,
'field_id' => 87,
'locale' => 'en',
'name' => 'anomaly.module.users::field.permissions.name',
'placeholder' => 'anomaly.module.users::field.permissions.placeholder',
'warning' => 'anomaly.module.users::field.permissions.warning',
'instructions' => 'anomaly.module.users::field.permissions.instructions',
],
],
],
'translations' => [
[
'id' => 98,
'assignment_id' => 98,
'locale' => 'en',
'label' => 'anomaly.module.users::field.permissions.label.users',
'warning' => 'anomaly.module.users::field.permissions.warning.users',
'placeholder' => 'anomaly.module.users::field.permissions.placeholder.users',
'instructions' => 'anomaly.module.users::field.permissions.instructions.users',
],
],
],
[
'id' => 99,
'sort_order' => 98,
'stream_id' => 12,
'field_id' => 85,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '85',
'namespace' => 'users',
'slug' => 'last_login_at',
'type' => 'anomaly.field_type.datetime',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 85,
'field_id' => 85,
'locale' => 'en',
'name' => 'anomaly.module.users::field.last_login_at.name',
'placeholder' => 'anomaly.module.users::field.last_login_at.placeholder',
'warning' => 'anomaly.module.users::field.last_login_at.warning',
'instructions' => 'anomaly.module.users::field.last_login_at.instructions',
],
],
],
'translations' => [
[
'id' => 99,
'assignment_id' => 99,
'locale' => 'en',
'label' => 'anomaly.module.users::field.last_login_at.label.users',
'warning' => 'anomaly.module.users::field.last_login_at.warning.users',
'placeholder' => 'anomaly.module.users::field.last_login_at.placeholder.users',
'instructions' => 'anomaly.module.users::field.last_login_at.instructions.users',
],
],
],
[
'id' => 100,
'sort_order' => 99,
'stream_id' => 12,
'field_id' => 83,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '83',
'namespace' => 'users',
'slug' => 'remember_token',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 83,
'field_id' => 83,
'locale' => 'en',
'name' => 'anomaly.module.users::field.remember_token.name',
'placeholder' => 'anomaly.module.users::field.remember_token.placeholder',
'warning' => 'anomaly.module.users::field.remember_token.warning',
'instructions' => 'anomaly.module.users::field.remember_token.instructions',
],
],
],
'translations' => [
[
'id' => 100,
'assignment_id' => 100,
'locale' => 'en',
'label' => 'anomaly.module.users::field.remember_token.label.users',
'warning' => 'anomaly.module.users::field.remember_token.warning.users',
'placeholder' => 'anomaly.module.users::field.remember_token.placeholder.users',
'instructions' => 'anomaly.module.users::field.remember_token.instructions.users',
],
],
],
[
'id' => 101,
'sort_order' => 100,
'stream_id' => 12,
'field_id' => 95,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '95',
'namespace' => 'users',
'slug' => 'activation_code',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 95,
'field_id' => 95,
'locale' => 'en',
'name' => 'anomaly.module.users::field.activation_code.name',
'placeholder' => 'anomaly.module.users::field.activation_code.placeholder',
'warning' => 'anomaly.module.users::field.activation_code.warning',
'instructions' => 'anomaly.module.users::field.activation_code.instructions',
],
],
],
'translations' => [
[
'id' => 101,
'assignment_id' => 101,
'locale' => 'en',
'label' => 'anomaly.module.users::field.activation_code.label.users',
'warning' => 'anomaly.module.users::field.activation_code.warning.users',
'placeholder' => 'anomaly.module.users::field.activation_code.placeholder.users',
'instructions' => 'anomaly.module.users::field.activation_code.instructions.users',
],
],
],
[
'id' => 102,
'sort_order' => 101,
'stream_id' => 12,
'field_id' => 93,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '93',
'namespace' => 'users',
'slug' => 'reset_code',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 93,
'field_id' => 93,
'locale' => 'en',
'name' => 'anomaly.module.users::field.reset_code.name',
'placeholder' => 'anomaly.module.users::field.reset_code.placeholder',
'warning' => 'anomaly.module.users::field.reset_code.warning',
'instructions' => 'anomaly.module.users::field.reset_code.instructions',
],
],
],
'translations' => [
[
'id' => 102,
'assignment_id' => 102,
'locale' => 'en',
'label' => 'anomaly.module.users::field.reset_code.label.users',
'warning' => 'anomaly.module.users::field.reset_code.warning.users',
'placeholder' => 'anomaly.module.users::field.reset_code.placeholder.users',
'instructions' => 'anomaly.module.users::field.reset_code.instructions.users',
],
],
],
[
'id' => 103,
'sort_order' => 102,
'stream_id' => 12,
'field_id' => 86,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '86',
'namespace' => 'users',
'slug' => 'last_activity_at',
'type' => 'anomaly.field_type.datetime',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 86,
'field_id' => 86,
'locale' => 'en',
'name' => 'anomaly.module.users::field.last_activity_at.name',
'placeholder' => 'anomaly.module.users::field.last_activity_at.placeholder',
'warning' => 'anomaly.module.users::field.last_activity_at.warning',
'instructions' => 'anomaly.module.users::field.last_activity_at.instructions',
],
],
],
'translations' => [
[
'id' => 103,
'assignment_id' => 103,
'locale' => 'en',
'label' => 'anomaly.module.users::field.last_activity_at.label.users',
'warning' => 'anomaly.module.users::field.last_activity_at.warning.users',
'placeholder' => 'anomaly.module.users::field.last_activity_at.placeholder.users',
'instructions' => 'anomaly.module.users::field.last_activity_at.instructions.users',
],
],
],
[
'id' => 104,
'sort_order' => 103,
'stream_id' => 12,
'field_id' => 84,
'config' => 'a:0:{}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '84',
'namespace' => 'users',
'slug' => 'ip_address',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 84,
'field_id' => 84,
'locale' => 'en',
'name' => 'anomaly.module.users::field.ip_address.name',
'placeholder' => 'anomaly.module.users::field.ip_address.placeholder',
'warning' => 'anomaly.module.users::field.ip_address.warning',
'instructions' => 'anomaly.module.users::field.ip_address.instructions',
],
],
],
'translations' => [
[
'id' => 104,
'assignment_id' => 104,
'locale' => 'en',
'label' => 'anomaly.module.users::field.ip_address.label.users',
'warning' => 'anomaly.module.users::field.ip_address.warning.users',
'placeholder' => 'anomaly.module.users::field.ip_address.placeholder.users',
'instructions' => 'anomaly.module.users::field.ip_address.instructions.users',
],
],
],
[
'id' => 109,
'sort_order' => 108,
'stream_id' => 12,
'field_id' => 101,
'config' => 'a:0:{}',
'unique' => 1,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '101',
'namespace' => 'users',
'slug' => 'str_id',
'type' => 'anomaly.field_type.text',
'config' => 'a:0:{}',
'locked' => '1',
'translations' => [
[
'id' => 101,
'field_id' => 101,
'locale' => 'en',
'name' => 'anomaly.module.users::field.str_id.name',
'placeholder' => 'anomaly.module.users::field.str_id.placeholder',
'warning' => 'anomaly.module.users::field.str_id.warning',
'instructions' => 'anomaly.module.users::field.str_id.instructions',
],
],
],
'translations' => [
[
'id' => 109,
'assignment_id' => 109,
'locale' => 'en',
'label' => 'anomaly.module.users::field.str_id.label.users',
'warning' => 'anomaly.module.users::field.str_id.warning.users',
'placeholder' => 'anomaly.module.users::field.str_id.placeholder.users',
'instructions' => 'anomaly.module.users::field.str_id.instructions.users',
],
],
],
],
'translations' => [
[
'id' => 12,
'stream_id' => 12,
'locale' => 'en',
'name' => 'anomaly.module.users::stream.users.name',
'description' => 'anomaly.module.users::stream.users.description',
],
],
];

    
    /**
     * The roles relation
     *
     * @return Relation
     */
    public function roles()
    {
        return $this->getFieldType('roles')->getRelation();
    }

}
