<?php namespace Anomaly\Streams\Platform\Model\Knowledge;

use Anomaly\Streams\Platform\Entry\EntryModel;

class KnowledgeKnowledgeEntryModel extends EntryModel
{

    use \Illuminate\Database\Eloquent\SoftDeletes;

    protected $searchable = true;

    protected $versionable = true;

    protected $table = 'knowledge_knowledge';

    protected $titleName = 'title';

    protected $rules = [
        'title' => '',
        'slug' => 'unique:knowledge_knowledge,slug',
        'publish_at' => '',
        'category' => 'required',
        'hide_header' => '',
        'image' => '',
        'content' => '',
        'youtube_url' => '',
        'buyers_guides_content' => '',
        'buyers_guides_pdfs' => '',
        'enabled' => '',
        'k_hidden' => '',
];

    protected $fields = [
        'title',
        'slug',
        'publish_at',
        'category',
        'hide_header',
        'image',
        'content',
        'youtube_url',
        'buyers_guides_content',
        'buyers_guides_pdfs',
        'enabled',
        'k_hidden',
];

    protected $with = ["translations"];

    protected $dates = ['created_at', 'updated_at', 'publish_at', 'deleted_at'];

    protected $relationships = ['category', 'image', 'content', 'buyers_guides_pdfs'];

    protected $translatedAttributes = ['title'];

    protected $translationForeignKey = 'entry_id';

    protected $translationModel = 'Anomaly\Streams\Platform\Model\Knowledge\KnowledgeKnowledgeEntryTranslationsModel';

    protected $stream = [
'id' => '87',
'sort_order' => '',
'namespace' => 'knowledge',
'slug' => 'knowledge',
'prefix' => 'knowledge_',
'title_column' => 'title',
'order_by' => 'id',
'locked' => '0',
'hidden' => '0',
'sortable' => '0',
'searchable' => '1',
'trashable' => '1',
'translatable' => '1',
'versionable' => '1',
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'assignments' => [
[
'id' => 348,
'sort_order' => 1,
'stream_id' => 87,
'field_id' => 264,
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'unique' => 0,
'required' => 0,
'searchable' => 1,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '264',
'namespace' => 'knowledge',
'slug' => 'title',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 543,
'field_id' => 264,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 544,
'field_id' => 264,
'locale' => 'en',
'name' => 'Title',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 545,
'field_id' => 264,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 546,
'field_id' => 264,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 813,
'assignment_id' => 348,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 814,
'assignment_id' => 348,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 815,
'assignment_id' => 348,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 816,
'assignment_id' => 348,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 347,
'sort_order' => 2,
'stream_id' => 87,
'field_id' => 265,
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'unique' => 1,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '265',
'namespace' => 'knowledge',
'slug' => 'slug',
'type' => 'anomaly.field_type.slug',
'config' => 'a:5:{s:4:"type";s:1:"_";s:7:"slugify";s:5:"title";s:9:"lowercase";b:1;s:3:"min";N;s:3:"max";N;}',
'locked' => '0',
'translations' => [
[
'id' => 547,
'field_id' => 265,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 548,
'field_id' => 265,
'locale' => 'en',
'name' => 'Slug',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 549,
'field_id' => 265,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 550,
'field_id' => 265,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 809,
'assignment_id' => 347,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 810,
'assignment_id' => 347,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 811,
'assignment_id' => 347,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 812,
'assignment_id' => 347,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 346,
'sort_order' => 3,
'stream_id' => 87,
'field_id' => 266,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '266',
'namespace' => 'knowledge',
'slug' => 'publish_at',
'type' => 'anomaly.field_type.datetime',
'config' => 'a:6:{s:4:"mode";s:8:"datetime";s:6:"picker";b:1;s:11:"date_format";s:5:"Y-m-d";s:11:"time_format";s:3:"H:i";s:8:"timezone";s:3:"UTC";s:4:"step";s:1:"1";}',
'locked' => '0',
'translations' => [
[
'id' => 551,
'field_id' => 266,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 552,
'field_id' => 266,
'locale' => 'en',
'name' => 'Publish at',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 553,
'field_id' => 266,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 554,
'field_id' => 266,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 805,
'assignment_id' => 346,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 806,
'assignment_id' => 346,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 807,
'assignment_id' => 346,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 808,
'assignment_id' => 346,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 345,
'sort_order' => 4,
'stream_id' => 87,
'field_id' => 270,
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'unique' => 0,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '270',
'namespace' => 'knowledge',
'slug' => 'category',
'type' => 'anomaly.field_type.relationship',
'config' => 'a:3:{s:7:"related";s:70:"Anomaly\Streams\Platform\Model\Knowledge\KnowledgeCategoriesEntryModel";s:4:"mode";s:8:"dropdown";s:10:"title_name";s:5:"title";}',
'locked' => '0',
'translations' => [
[
'id' => 567,
'field_id' => 270,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 568,
'field_id' => 270,
'locale' => 'en',
'name' => 'Category',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 569,
'field_id' => 270,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 570,
'field_id' => 270,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 801,
'assignment_id' => 345,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 802,
'assignment_id' => 345,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 803,
'assignment_id' => 345,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 804,
'assignment_id' => 345,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 408,
'sort_order' => 5,
'stream_id' => 87,
'field_id' => 306,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '306',
'namespace' => 'knowledge',
'slug' => 'hide_header',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:7:{s:4:"mode";s:6:"switch";s:5:"label";N;s:7:"on_text";N;s:8:"on_color";s:7:"success";s:8:"off_text";N;s:9:"off_color";s:7:"default";s:13:"default_value";b:0;}',
'locked' => '0',
'translations' => [
[
'id' => 711,
'field_id' => 306,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 712,
'field_id' => 306,
'locale' => 'en',
'name' => 'Hide header',
'placeholder' => '',
'warning' => '',
'instructions' => 'This switch hide header in inner page',
],
[
'id' => 713,
'field_id' => 306,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 714,
'field_id' => 306,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 1053,
'assignment_id' => 408,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1054,
'assignment_id' => 408,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1055,
'assignment_id' => 408,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1056,
'assignment_id' => 408,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 344,
'sort_order' => 6,
'stream_id' => 87,
'field_id' => 267,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '267',
'namespace' => 'knowledge',
'slug' => 'image',
'type' => 'anomaly.field_type.image',
'config' => 'a:3:{s:7:"folders";a:1:{i:0;s:1:"1";}s:12:"aspect_ratio";N;s:4:"mode";s:7:"default";}',
'locked' => '0',
'translations' => [
[
'id' => 555,
'field_id' => 267,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 556,
'field_id' => 267,
'locale' => 'en',
'name' => 'Image',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 557,
'field_id' => 267,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 558,
'field_id' => 267,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 797,
'assignment_id' => 344,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 798,
'assignment_id' => 344,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 799,
'assignment_id' => 344,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 800,
'assignment_id' => 344,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 343,
'sort_order' => 7,
'stream_id' => 87,
'field_id' => 269,
'config' => 'a:1:{i:0;s:59:"a:1:{i:0;s:41:"a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}";}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '269',
'namespace' => 'knowledge',
'slug' => 'content',
'type' => 'anomaly.field_type.grid',
'config' => 'a:4:{s:7:"related";N;s:7:"add_row";N;s:3:"min";N;s:3:"max";N;}',
'locked' => '0',
'translations' => [
[
'id' => 563,
'field_id' => 269,
'locale' => 'ar',
'name' => 'Content',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 564,
'field_id' => 269,
'locale' => 'en',
'name' => 'Content',
'placeholder' => '',
'warning' => '',
'instructions' => 'Only for <b> Whitepapers </b> category pages',
],
[
'id' => 565,
'field_id' => 269,
'locale' => 'de',
'name' => 'Content',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 566,
'field_id' => 269,
'locale' => 'es',
'name' => 'Content',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 793,
'assignment_id' => 343,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => 'Only for <b>Case Study</b> pages',
],
[
'id' => 794,
'assignment_id' => 343,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => 'Only for <b> Whitepapers </b> category pages',
],
[
'id' => 795,
'assignment_id' => 343,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => 'Only for <b>Case Study</b> pages',
],
[
'id' => 796,
'assignment_id' => 343,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => 'Only for <b>Case Study</b> pages',
],
],
],
[
'id' => 362,
'sort_order' => 8,
'stream_id' => 87,
'field_id' => 273,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '273',
'namespace' => 'knowledge',
'slug' => 'youtube_url',
'type' => 'anomaly.field_type.url',
'config' => 'a:1:{s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 579,
'field_id' => 273,
'locale' => 'ar',
'name' => 'Youtube URL',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 580,
'field_id' => 273,
'locale' => 'en',
'name' => 'Youtube URL',
'placeholder' => '',
'warning' => '',
'instructions' => 'Only for <b>Videos</b> category pages',
],
[
'id' => 581,
'field_id' => 273,
'locale' => 'de',
'name' => 'Youtube URL',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 582,
'field_id' => 273,
'locale' => 'es',
'name' => 'Youtube URL',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 869,
'assignment_id' => 362,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 870,
'assignment_id' => 362,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => 'Only for <b>Videos</b> category',
],
[
'id' => 871,
'assignment_id' => 362,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 872,
'assignment_id' => 362,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 364,
'sort_order' => 9,
'stream_id' => 87,
'field_id' => 274,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '274',
'namespace' => 'knowledge',
'slug' => 'buyers_guides_content',
'type' => 'anomaly.field_type.wysiwyg',
'config' => 'a:6:{s:7:"buttons";a:8:{i:0;s:6:"format";i:1;s:4:"bold";i:2;s:6:"italic";i:3;s:7:"deleted";i:4;s:5:"lists";i:5;s:4:"link";i:6;s:14:"horizontalrule";i:7;s:9:"underline";}s:7:"plugins";a:8:{i:0;s:9:"alignment";i:1;s:11:"inlinestyle";i:2;s:5:"table";i:3;s:5:"video";i:4;s:11:"filemanager";i:5;s:12:"imagemanager";i:6;s:6:"source";i:7;s:10:"fullscreen";}s:6:"height";s:2:"75";s:11:"line_breaks";b:0;s:16:"remove_new_lines";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 583,
'field_id' => 274,
'locale' => 'ar',
'name' => 'Content (Buyer’s guides)',
'placeholder' => '',
'warning' => '',
'instructions' => 'Only for <b>Buyer’s guides</b> category pages',
],
[
'id' => 584,
'field_id' => 274,
'locale' => 'en',
'name' => 'Content (Buyer’s guides, case studies, brochures)',
'placeholder' => '',
'warning' => '',
'instructions' => 'Only for <b>Buyer’s guides, case studies, brochures</b> category pages',
],
[
'id' => 585,
'field_id' => 274,
'locale' => 'de',
'name' => 'Content (Buyer’s guides)',
'placeholder' => '',
'warning' => '',
'instructions' => 'Only for <b>Buyer’s guides</b> category pages',
],
[
'id' => 586,
'field_id' => 274,
'locale' => 'es',
'name' => 'Content (Buyer’s guides)',
'placeholder' => '',
'warning' => '',
'instructions' => 'Only for <b>Buyer’s guides</b> category pages',
],
],
],
'translations' => [
[
'id' => 877,
'assignment_id' => 364,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 878,
'assignment_id' => 364,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 879,
'assignment_id' => 364,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 880,
'assignment_id' => 364,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 363,
'sort_order' => 10,
'stream_id' => 87,
'field_id' => 275,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '275',
'namespace' => 'knowledge',
'slug' => 'buyers_guides_pdfs',
'type' => 'anomaly.field_type.files',
'config' => 'a:5:{s:7:"folders";a:1:{i:0;s:1:"2";}s:3:"min";N;s:3:"max";N;s:4:"mode";s:7:"default";s:13:"allowed_types";a:1:{i:0;s:3:"pdf";}}',
'locked' => '0',
'translations' => [
[
'id' => 587,
'field_id' => 275,
'locale' => 'ar',
'name' => 'Buyer’s guides PDFs',
'placeholder' => '',
'warning' => '',
'instructions' => 'Only for <b>Buyer’s guides</b> category pages',
],
[
'id' => 588,
'field_id' => 275,
'locale' => 'en',
'name' => 'Buyer’s guides PDFs (also case studies, brochures)',
'placeholder' => '',
'warning' => '',
'instructions' => 'Only for <b>Buyer’s guides, case studies, brochures</b> category pages',
],
[
'id' => 589,
'field_id' => 275,
'locale' => 'de',
'name' => 'Buyer’s guides PDFs',
'placeholder' => '',
'warning' => '',
'instructions' => 'Only for <b>Buyer’s guides</b> category pages',
],
[
'id' => 590,
'field_id' => 275,
'locale' => 'es',
'name' => 'Buyer’s guides PDFs',
'placeholder' => '',
'warning' => '',
'instructions' => 'Only for <b>Buyer’s guides</b> category pages',
],
],
],
'translations' => [
[
'id' => 873,
'assignment_id' => 363,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 874,
'assignment_id' => 363,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 875,
'assignment_id' => 363,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 876,
'assignment_id' => 363,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 342,
'sort_order' => 11,
'stream_id' => 87,
'field_id' => 268,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '268',
'namespace' => 'knowledge',
'slug' => 'enabled',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:7:{s:4:"mode";s:6:"switch";s:5:"label";N;s:7:"on_text";N;s:8:"on_color";s:7:"success";s:8:"off_text";N;s:9:"off_color";s:7:"default";s:13:"default_value";b:0;}',
'locked' => '0',
'translations' => [
[
'id' => 559,
'field_id' => 268,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 560,
'field_id' => 268,
'locale' => 'en',
'name' => 'Enabled',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 561,
'field_id' => 268,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 562,
'field_id' => 268,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 789,
'assignment_id' => 342,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 790,
'assignment_id' => 342,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 791,
'assignment_id' => 342,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 792,
'assignment_id' => 342,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 409,
'sort_order' => 368,
'stream_id' => 87,
'field_id' => 307,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '307',
'namespace' => 'knowledge',
'slug' => 'k_hidden',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:7:{s:4:"mode";s:6:"switch";s:5:"label";N;s:7:"on_text";N;s:8:"on_color";s:7:"warning";s:8:"off_text";N;s:9:"off_color";s:7:"default";s:13:"default_value";b:0;}',
'locked' => '0',
'translations' => [
[
'id' => 715,
'field_id' => 307,
'locale' => 'ar',
'name' => 'Hidden',
'placeholder' => '',
'warning' => '',
'instructions' => 'Is this article is hidden in frontend?',
],
[
'id' => 716,
'field_id' => 307,
'locale' => 'en',
'name' => 'Hidden',
'placeholder' => '',
'warning' => '',
'instructions' => 'Is this article is hidden in frontend?',
],
[
'id' => 717,
'field_id' => 307,
'locale' => 'de',
'name' => 'Hidden',
'placeholder' => '',
'warning' => '',
'instructions' => 'Is this article is hidden in frontend?',
],
[
'id' => 718,
'field_id' => 307,
'locale' => 'es',
'name' => 'Hidden',
'placeholder' => '',
'warning' => '',
'instructions' => 'Is this article is hidden in frontend?',
],
],
],
'translations' => [
[
'id' => 1057,
'assignment_id' => 409,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1058,
'assignment_id' => 409,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1059,
'assignment_id' => 409,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1060,
'assignment_id' => 409,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
],
'translations' => [
[
'id' => 225,
'stream_id' => 87,
'locale' => 'ar',
'name' => '',
'description' => '',
],
[
'id' => 226,
'stream_id' => 87,
'locale' => 'en',
'name' => 'Knowledge centre',
'description' => '',
],
[
'id' => 227,
'stream_id' => 87,
'locale' => 'de',
'name' => '',
'description' => '',
],
[
'id' => 228,
'stream_id' => 87,
'locale' => 'es',
'name' => '',
'description' => '',
],
],
];

    
    /**
     * The category relation
     *
     * @return Relation
     */
    public function category()
    {
        return $this->getFieldType('category')->getRelation();
    }

    /**
     * The image relation
     *
     * @return Relation
     */
    public function image()
    {
        return $this->getFieldType('image')->getRelation();
    }

    /**
     * The content relation
     *
     * @return Relation
     */
    public function content()
    {
        return $this->getFieldType('content')->getRelation();
    }

    /**
     * The buyers guides pdfs relation
     *
     * @return Relation
     */
    public function buyersGuidesPdfs()
    {
        return $this->getFieldType('buyers_guides_pdfs')->getRelation();
    }

}
