<?php namespace Anomaly\Streams\Platform\Model\Products;

use Anomaly\Streams\Platform\Entry\EntryModel;

class ProductsProductsEntryModel extends EntryModel
{

    use \Illuminate\Database\Eloquent\SoftDeletes;

    protected $searchable = true;

    protected $versionable = true;

    protected $table = 'products_products';

    protected $titleName = 'title';

    protected $rules = [
        'title' => '',
        'slug' => '',
        'brand' => 'required',
        'category' => 'required',
        'component_group' => 'required',
        'gallery' => '',
        'description' => '',
        'product_variations' => '',
        'whitepapers_en' => '',
        'enabled' => '',
        'meta_title' => '',
        'meta_description' => '',
];

    protected $fields = [
        'title',
        'slug',
        'brand',
        'category',
        'component_group',
        'gallery',
        'description',
        'product_variations',
        'whitepapers_en',
        'enabled',
        'meta_title',
        'meta_description',
];

    protected $with = ["translations"];

    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    protected $relationships = ['brand', 'category', 'component_group', 'gallery', 'product_variations', 'whitepapers_en'];

    protected $translatedAttributes = ['title', 'slug', 'description', 'meta_title', 'meta_description'];

    protected $translationForeignKey = 'entry_id';

    protected $translationModel = 'Anomaly\Streams\Platform\Model\Products\ProductsProductsEntryTranslationsModel';

    protected $stream = [
'id' => '44',
'sort_order' => '1',
'namespace' => 'products',
'slug' => 'products',
'prefix' => 'products_',
'title_column' => 'title',
'order_by' => 'id',
'locked' => '0',
'hidden' => '0',
'sortable' => '1',
'searchable' => '1',
'trashable' => '1',
'translatable' => '1',
'versionable' => '1',
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'assignments' => [
[
'id' => 202,
'sort_order' => 1,
'stream_id' => 44,
'field_id' => 174,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 1,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '174',
'namespace' => 'products',
'slug' => 'title',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 186,
'field_id' => 174,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 187,
'field_id' => 174,
'locale' => 'en',
'name' => 'Title',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 188,
'field_id' => 174,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 189,
'field_id' => 174,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 232,
'assignment_id' => 202,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 233,
'assignment_id' => 202,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 234,
'assignment_id' => 202,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 235,
'assignment_id' => 202,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 215,
'sort_order' => 2,
'stream_id' => 44,
'field_id' => 188,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '188',
'namespace' => 'products',
'slug' => 'slug',
'type' => 'anomaly.field_type.slug',
'config' => 'a:5:{s:4:"type";s:1:"-";s:7:"slugify";s:5:"title";s:9:"lowercase";b:1;s:3:"min";N;s:3:"max";N;}',
'locked' => '0',
'translations' => [
[
'id' => 236,
'field_id' => 188,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 237,
'field_id' => 188,
'locale' => 'en',
'name' => 'Slug',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 238,
'field_id' => 188,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 239,
'field_id' => 188,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 284,
'assignment_id' => 215,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 285,
'assignment_id' => 215,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 286,
'assignment_id' => 215,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 287,
'assignment_id' => 215,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 203,
'sort_order' => 3,
'stream_id' => 44,
'field_id' => 177,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 1,
'searchable' => 1,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '177',
'namespace' => 'products',
'slug' => 'brand',
'type' => 'anomaly.field_type.relationship',
'config' => 'a:3:{s:7:"related";s:64:"Anomaly\Streams\Platform\Model\Products\ProductsBrandsEntryModel";s:4:"mode";s:6:"search";s:10:"title_name";s:5:"title";}',
'locked' => '0',
'translations' => [
[
'id' => 192,
'field_id' => 177,
'locale' => 'ar',
'name' => 'Brand',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 193,
'field_id' => 177,
'locale' => 'en',
'name' => 'Brand',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 194,
'field_id' => 177,
'locale' => 'de',
'name' => 'Brand',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 195,
'field_id' => 177,
'locale' => 'es',
'name' => 'Brand',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 236,
'assignment_id' => 203,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 237,
'assignment_id' => 203,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 238,
'assignment_id' => 203,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 239,
'assignment_id' => 203,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 204,
'sort_order' => 4,
'stream_id' => 44,
'field_id' => 178,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 1,
'searchable' => 1,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '178',
'namespace' => 'products',
'slug' => 'category',
'type' => 'anomaly.field_type.relationship',
'config' => 'a:3:{s:7:"related";s:68:"Anomaly\Streams\Platform\Model\Products\ProductsCategoriesEntryModel";s:4:"mode";s:6:"search";s:10:"title_name";s:5:"title";}',
'locked' => '0',
'translations' => [
[
'id' => 196,
'field_id' => 178,
'locale' => 'ar',
'name' => 'Category',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 197,
'field_id' => 178,
'locale' => 'en',
'name' => 'Category',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 198,
'field_id' => 178,
'locale' => 'de',
'name' => 'Category',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 199,
'field_id' => 178,
'locale' => 'es',
'name' => 'Category',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 240,
'assignment_id' => 204,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 241,
'assignment_id' => 204,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 242,
'assignment_id' => 204,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 243,
'assignment_id' => 204,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 220,
'sort_order' => 5,
'stream_id' => 44,
'field_id' => 190,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 1,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '190',
'namespace' => 'products',
'slug' => 'component_group',
'type' => 'anomaly.field_type.relationship',
'config' => 'a:3:{s:7:"related";s:74:"Anomaly\Streams\Platform\Model\Products\ProductsComponentsGroupsEntryModel";s:4:"mode";s:6:"search";s:10:"title_name";s:5:"title";}',
'locked' => '0',
'translations' => [
[
'id' => 244,
'field_id' => 190,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 245,
'field_id' => 190,
'locale' => 'en',
'name' => 'Component group',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 246,
'field_id' => 190,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 247,
'field_id' => 190,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 304,
'assignment_id' => 220,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 305,
'assignment_id' => 220,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 306,
'assignment_id' => 220,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 307,
'assignment_id' => 220,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 205,
'sort_order' => 6,
'stream_id' => 44,
'field_id' => 179,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '179',
'namespace' => 'products',
'slug' => 'gallery',
'type' => 'anomaly.field_type.files',
'config' => 'a:5:{s:7:"folders";a:1:{i:0;s:1:"3";}s:3:"min";N;s:3:"max";N;s:4:"mode";s:7:"default";s:13:"allowed_types";a:0:{}}',
'locked' => '0',
'translations' => [
[
'id' => 200,
'field_id' => 179,
'locale' => 'ar',
'name' => 'Gaoo',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 201,
'field_id' => 179,
'locale' => 'en',
'name' => 'Gallery',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 202,
'field_id' => 179,
'locale' => 'de',
'name' => 'Gaoo',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 203,
'field_id' => 179,
'locale' => 'es',
'name' => 'Gaoo',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 244,
'assignment_id' => 205,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 245,
'assignment_id' => 205,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 246,
'assignment_id' => 205,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 247,
'assignment_id' => 205,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 206,
'sort_order' => 7,
'stream_id' => 44,
'field_id' => 180,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '180',
'namespace' => 'products',
'slug' => 'description',
'type' => 'anomaly.field_type.wysiwyg',
'config' => 'a:6:{s:7:"buttons";a:2:{i:0;s:4:"bold";i:1;s:4:"link";}s:7:"plugins";a:2:{i:0;s:6:"source";i:1;s:10:"fullscreen";}s:6:"height";s:3:"150";s:11:"line_breaks";b:0;s:16:"remove_new_lines";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 204,
'field_id' => 180,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 205,
'field_id' => 180,
'locale' => 'en',
'name' => 'Description',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 206,
'field_id' => 180,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 207,
'field_id' => 180,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 248,
'assignment_id' => 206,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 249,
'assignment_id' => 206,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 250,
'assignment_id' => 206,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 251,
'assignment_id' => 206,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 208,
'sort_order' => 8,
'stream_id' => 44,
'field_id' => 182,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '182',
'namespace' => 'products',
'slug' => 'product_variations',
'type' => 'anomaly.field_type.repeater',
'config' => 'a:5:{s:7:"related";s:75:"Anomaly\Streams\Platform\Model\Repeater\RepeaterProductVariationsEntryModel";s:7:"add_row";s:17:"Add New Variation";s:3:"min";N;s:3:"max";N;s:14:"repeater_title";s:5:"title";}',
'locked' => '0',
'translations' => [
[
'id' => 212,
'field_id' => 182,
'locale' => 'ar',
'name' => 'Product variations',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 213,
'field_id' => 182,
'locale' => 'en',
'name' => 'Product variations',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 214,
'field_id' => 182,
'locale' => 'de',
'name' => 'Product variations',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 215,
'field_id' => 182,
'locale' => 'es',
'name' => 'Product variations',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 256,
'assignment_id' => 208,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 257,
'assignment_id' => 208,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 258,
'assignment_id' => 208,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 259,
'assignment_id' => 208,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 219,
'sort_order' => 9,
'stream_id' => 44,
'field_id' => 189,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '189',
'namespace' => 'products',
'slug' => 'whitepapers_en',
'type' => 'anomaly.field_type.files',
'config' => 'a:5:{s:7:"folders";a:1:{i:0;s:1:"2";}s:3:"min";N;s:3:"max";N;s:4:"mode";s:7:"default";s:13:"allowed_types";a:1:{i:0;s:3:"pdf";}}',
'locked' => '0',
'translations' => [
[
'id' => 240,
'field_id' => 189,
'locale' => 'ar',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 241,
'field_id' => 189,
'locale' => 'en',
'name' => 'Whitepapers',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 242,
'field_id' => 189,
'locale' => 'de',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 243,
'field_id' => 189,
'locale' => 'es',
'name' => '',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 300,
'assignment_id' => 219,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 301,
'assignment_id' => 219,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 302,
'assignment_id' => 219,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 303,
'assignment_id' => 219,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 242,
'sort_order' => 10,
'stream_id' => 44,
'field_id' => 208,
'config' => 'a:1:{i:0;s:6:"a:0:{}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 0,
'versionable' => 0,
'field' => [
'id' => '208',
'namespace' => 'products',
'slug' => 'enabled',
'type' => 'anomaly.field_type.boolean',
'config' => 'a:7:{s:4:"mode";s:6:"switch";s:5:"label";N;s:7:"on_text";N;s:8:"on_color";s:7:"success";s:8:"off_text";N;s:9:"off_color";s:7:"default";s:13:"default_value";b:1;}',
'locked' => '0',
'translations' => [
[
'id' => 319,
'field_id' => 208,
'locale' => 'ar',
'name' => 'Enabled',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 320,
'field_id' => 208,
'locale' => 'en',
'name' => 'Enabled',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 321,
'field_id' => 208,
'locale' => 'de',
'name' => 'Enabled',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 322,
'field_id' => 208,
'locale' => 'es',
'name' => 'Enabled',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 392,
'assignment_id' => 242,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 393,
'assignment_id' => 242,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 394,
'assignment_id' => 242,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 395,
'assignment_id' => 242,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 402,
'sort_order' => 12,
'stream_id' => 44,
'field_id' => 300,
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '300',
'namespace' => 'products',
'slug' => 'meta_title',
'type' => 'anomaly.field_type.text',
'config' => 'a:6:{s:4:"type";s:4:"text";s:4:"mask";N;s:3:"min";N;s:3:"max";s:3:"255";s:12:"show_counter";b:0;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 687,
'field_id' => 300,
'locale' => 'ar',
'name' => 'meta_title',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 688,
'field_id' => 300,
'locale' => 'en',
'name' => 'Meta title',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 689,
'field_id' => 300,
'locale' => 'de',
'name' => 'meta_title',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 690,
'field_id' => 300,
'locale' => 'es',
'name' => 'meta_title',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 1029,
'assignment_id' => 402,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1030,
'assignment_id' => 402,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1031,
'assignment_id' => 402,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1032,
'assignment_id' => 402,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
[
'id' => 403,
'sort_order' => 13,
'stream_id' => 44,
'field_id' => 301,
'config' => 'a:1:{i:0;s:23:"a:1:{i:0;s:6:"a:0:{}";}";}',
'unique' => 0,
'required' => 0,
'searchable' => 0,
'translatable' => 1,
'versionable' => 0,
'field' => [
'id' => '301',
'namespace' => 'products',
'slug' => 'meta_description',
'type' => 'anomaly.field_type.textarea',
'config' => 'a:6:{s:4:"rows";s:1:"6";s:3:"min";N;s:3:"max";N;s:12:"show_counter";b:0;s:8:"autogrow";b:1;s:13:"default_value";N;}',
'locked' => '0',
'translations' => [
[
'id' => 691,
'field_id' => 301,
'locale' => 'ar',
'name' => 'meta_description',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 692,
'field_id' => 301,
'locale' => 'en',
'name' => 'Meta description',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 693,
'field_id' => 301,
'locale' => 'de',
'name' => 'meta_description',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
[
'id' => 694,
'field_id' => 301,
'locale' => 'es',
'name' => 'meta_description',
'placeholder' => '',
'warning' => '',
'instructions' => '',
],
],
],
'translations' => [
[
'id' => 1033,
'assignment_id' => 403,
'locale' => 'ar',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1034,
'assignment_id' => 403,
'locale' => 'en',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1035,
'assignment_id' => 403,
'locale' => 'de',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
[
'id' => 1036,
'assignment_id' => 403,
'locale' => 'es',
'label' => '',
'warning' => '',
'placeholder' => '',
'instructions' => '',
],
],
],
],
'translations' => [
[
'id' => 71,
'stream_id' => 44,
'locale' => 'ar',
'name' => 'Products',
'description' => '',
],
[
'id' => 72,
'stream_id' => 44,
'locale' => 'en',
'name' => 'Products',
'description' => '',
],
[
'id' => 73,
'stream_id' => 44,
'locale' => 'de',
'name' => 'Products',
'description' => '',
],
[
'id' => 74,
'stream_id' => 44,
'locale' => 'es',
'name' => 'Products',
'description' => '',
],
],
];

    
    /**
     * The brand relation
     *
     * @return Relation
     */
    public function brand()
    {
        return $this->getFieldType('brand')->getRelation();
    }

    /**
     * The category relation
     *
     * @return Relation
     */
    public function category()
    {
        return $this->getFieldType('category')->getRelation();
    }

    /**
     * The component group relation
     *
     * @return Relation
     */
    public function componentGroup()
    {
        return $this->getFieldType('component_group')->getRelation();
    }

    /**
     * The gallery relation
     *
     * @return Relation
     */
    public function gallery()
    {
        return $this->getFieldType('gallery')->getRelation();
    }

    /**
     * The product variations relation
     *
     * @return Relation
     */
    public function productVariations()
    {
        return $this->getFieldType('product_variations')->getRelation();
    }

    /**
     * The whitepapers en relation
     *
     * @return Relation
     */
    public function whitepapersEn()
    {
        return $this->getFieldType('whitepapers_en')->getRelation();
    }

}
